"""
This is a setup.py script generated by py2applet
https://py2app.readthedocs.io/en/latest/tutorial.html#create-a-setup-py-file
https://github.com/r0x0r/pywebview/blob/master/examples/py2app_setup.py
https://pywebview.flowrl.com/guide/freezing.html#macos
Usage:
    python setup.py py2app
"""
import os
from setuptools import setup

def tree(src):
    return [(root, map(lambda f: os.path.join(root, f), files))
        for (root, dirs, files) in os.walk(os.path.normpath(src))]


ENTRY_POINT = ['pywebv.py']
DATA_FILES = tree('DATA_FILES_DIR') + tree('DATA_FILE_DIR2')
OPTIONS = {'argv_emulation': False,
           'strip': True,
           #'iconfile': 'icon.icns', # uncomment to include an icon
           'includes': ['WebKit', 'Foundation', 'webview']}

setup(
    app=ENTRY_POINT,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
